name: Hanspeter Stamm
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13994
title: Hanspeter Stamm Trumpeter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c4c4c4'
    - '#909090'
    - '#5f5f5f'
  brandStrength: 0.058582155499607325
  lightness: 0.5881041106767952
  saturation: 0.16643242142163217
  rhythmicContrast: 0.29573195497505367
purpose: []
