name: Hanspeter Stamm
favicon: null
layout_spectrum: 0.34584574843756855
typography_spectrum: 0.6574747876729816
title: Hanspeter Stamm Trumpeter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.058582155499607325
  lightness: 0.5881041106767952
  saturation: 0.16643242142163217
  rhythmicContrast: 0.29573195497505367
purpose: []
